name: Build macOS DMG (Unsigned)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build macOS
        run: npm run dist:mac

      - name: Upload artifact (.dmg)
        uses: actions/upload-artifact@v4
        with:
          name: Generador_Grilla_CGSCHILE_macOS_DMG
          path: dist/*.dmg
