name: Build Linux AppImage

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build Linux
        run: npm run dist:linux

      - name: Upload artifact (.AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: Generador_Grilla_CGSCHILE_Linux_AppImage
          path: dist/*.AppImage
