name: Build Windows Installer
on:
  workflow_dispatch:
  push: { branches: [ main, master ] }

jobs:
  build:
    runs-on: windows-latest
    env:
      # Fuerza logs útiles y evita publicar releases
      DEBUG: electron-builder
      CI: true
      GH_TOKEN: ""                               # evita auto-publish
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
      CSC_IDENTITY_AUTO_DISCOVERY: "false"       # desactiva intento de firma

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Mostrar versiones y árbol
        run: |
          node -v
          npm -v
          dir
          type package.json

      - name: Instalar dependencias
        run: |
          npm install --no-audit --no-fund || npm install --legacy-peer-deps --no-audit --no-fund

      - name: Pre-fetch builder
        run: npx electron-builder --version

      - name: Build Windows (.exe)
        run: npx electron-builder -w --publish=never

      - name: Upload outputs & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-and-logs
          path: |
            dist/**
            **/_logs/**
            **/builder-debug*.log
