name: Build Windows Installer
on:
  workflow_dispatch:
  push: { branches: [ main, master ] }

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'           # más estable para Electron 30
          cache: 'npm'

      # A veces npm install falla por peer deps. Probamos normal y, si falla, repetimos con legacy.
      - name: Install dependencies
        run: |
          npm install || (echo "retry with legacy peer deps" && npm install --legacy-peer-deps)

      # (Opcional) asegura binarios nativos de Electron si alguna lib los requiere
      - name: Install app deps
        run: npx electron-builder install-app-deps

      - name: Build Windows (.exe)
        run: npm run dist:win

      - name: Upload artifact (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: Generador_Grilla_CGSCHILE_Windows_Installer
          path: dist/*.exe
